// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Data;

namespace WebApplication1.Migrations
{
    [DbContext(typeof(WebApplication1Context))]
    partial class WebApplication1ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplication1.Models.Employee", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FGS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Old")
                        .HasColumnType("int");

                    b.Property<long?>("OrderID")
                        .HasColumnType("bigint");

                    b.Property<string>("Pasport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("PositionsID")
                        .HasColumnType("bigint");

                    b.Property<int>("Telefon")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("OrderID");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("WebApplication1.Models.Menu", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Cooking_time")
                        .HasColumnType("datetime2");

                    b.Property<int>("Cost")
                        .HasColumnType("int");

                    b.Property<long?>("Ingredient_1ID")
                        .HasColumnType("bigint");

                    b.Property<long?>("Ingredient_2ID")
                        .HasColumnType("bigint");

                    b.Property<long?>("Ingredient_3ID")
                        .HasColumnType("bigint");

                    b.Property<string>("Name_dish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("OrderID")
                        .HasColumnType("bigint");

                    b.Property<long?>("OrderID1")
                        .HasColumnType("bigint");

                    b.Property<long?>("OrderID2")
                        .HasColumnType("bigint");

                    b.Property<int>("Volume_Ingredient_1")
                        .HasColumnType("int");

                    b.Property<int>("Volume_Ingredient_2")
                        .HasColumnType("int");

                    b.Property<int>("Volume_Ingredient_3")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("OrderID");

                    b.HasIndex("OrderID1");

                    b.HasIndex("OrderID2");

                    b.ToTable("Menu");
                });

            modelBuilder.Entity("WebApplication1.Models.Order", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cost")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("FGS_employer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Telefon")
                        .HasColumnType("int");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("check")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("dish_1ID")
                        .HasColumnType("bigint");

                    b.Property<long?>("dish_2ID")
                        .HasColumnType("bigint");

                    b.Property<long?>("dish_3ID")
                        .HasColumnType("bigint");

                    b.Property<long?>("employeesID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("WebApplication1.Models.Position", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("EmployeeID")
                        .HasColumnType("bigint");

                    b.Property<string>("Name_Positions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Requirements")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Responsibilities")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("EmployeeID");

                    b.ToTable("Position");
                });

            modelBuilder.Entity("WebApplication1.Models.Warehouse", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cost")
                        .HasColumnType("int");

                    b.Property<string>("Incept_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("MenuID")
                        .HasColumnType("bigint");

                    b.Property<long?>("MenuID1")
                        .HasColumnType("bigint");

                    b.Property<long?>("MenuID2")
                        .HasColumnType("bigint");

                    b.Property<string>("Name_Ingredient")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Producer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Shelf_life")
                        .HasColumnType("datetime2");

                    b.Property<int>("Volume")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("MenuID");

                    b.HasIndex("MenuID1");

                    b.HasIndex("MenuID2");

                    b.ToTable("Warehouse");
                });

            modelBuilder.Entity("WebApplication1.Models.Employee", b =>
                {
                    b.HasOne("WebApplication1.Models.Order", null)
                        .WithMany("ID_employees")
                        .HasForeignKey("OrderID");
                });

            modelBuilder.Entity("WebApplication1.Models.Menu", b =>
                {
                    b.HasOne("WebApplication1.Models.Order", null)
                        .WithMany("dish_1")
                        .HasForeignKey("OrderID");

                    b.HasOne("WebApplication1.Models.Order", null)
                        .WithMany("dish_2")
                        .HasForeignKey("OrderID1");

                    b.HasOne("WebApplication1.Models.Order", null)
                        .WithMany("dish_3")
                        .HasForeignKey("OrderID2");
                });

            modelBuilder.Entity("WebApplication1.Models.Position", b =>
                {
                    b.HasOne("WebApplication1.Models.Employee", null)
                        .WithMany("ID_Positions")
                        .HasForeignKey("EmployeeID");
                });

            modelBuilder.Entity("WebApplication1.Models.Warehouse", b =>
                {
                    b.HasOne("WebApplication1.Models.Menu", null)
                        .WithMany("Ingredient_1")
                        .HasForeignKey("MenuID");

                    b.HasOne("WebApplication1.Models.Menu", null)
                        .WithMany("Ingredient_2")
                        .HasForeignKey("MenuID1");

                    b.HasOne("WebApplication1.Models.Menu", null)
                        .WithMany("Ingredient_3")
                        .HasForeignKey("MenuID2");
                });
#pragma warning restore 612, 618
        }
    }
}
